//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAjaxApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public string PRODID { get; set; }
        public string PRODNAME { get; set; }
        public Nullable<int> PRODPRICE { get; set; }
        public string CATEID { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
